#! /bin/bash

OPTIND=1         # Reset in case getopts has been used previously in the shell.

O=3
i=0
infile=""
outfile=""

usage() { echo "Required: (i)nfile, (o)utfile. Optional: (O)ptimisation level, (p)rofiling, (v|V)ersion, (h)elp."; }
version() { echo "elfcc, the elfcode compiler, version 1.1"; }

while getopts "pvVO:i:o:h" o; do
    case "${o}" in
        O)
            O=${OPTARG}
            ((O == 0 || O == 1 || O == 2 || O == 3)) || usage
            ;;
        v)
			version
            ;;
		V) 
			version
			;;
		p) 
			i=1
			;;
		i)
			infile=${OPTARG}
			;;
		o)
			outfile=${OPTARG}
			;;
        h)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ "$infile" == "" ] || [ "$outfile" == "" ]; then
    usage
	exit 1
fi

python3 elfcc.py $infile $i > temp.c
gcc -O$O -o $outfile temp.c
rm temp.c
